### YamlMime 
# Pipeline that builds and deploys componenten.

name: $(BuildDefinitionName)_$(GitVersion_SemVer)

trigger:
  batch: 'true'
  tags:
    include:
      - '*'
  branches:
    include: 
      - master

resources:
  repositories:
  - repository: PGGM.PipelineTemplates
    name: PGGM/PGGM.Web.Components.Pipeline
    type: git
    ref: 'refs/heads/master'

extends:
  template: deployments/templates/1.0.0.3/pfzw-build-and-deploy-to-azure.yml@PGGM.PipelineTemplates
  parameters:
    installChrome: false
